app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::group(['prefix' => LaravelLocalization::setLocale()], function() {

	Route::get('/', 				["as"=>"index", 		"uses"=>"Frontend\IndexController@index"]);
	Route::get('/category/{id}', 	['as'=>"category", 		'uses'=>'Frontend\IndexController@showProductByCategory']);
	Route::post('/auth/login', 		['as'=>'authLogin',		'uses'=>'Auth\AuthController@postLogin']);
	Route::get('/auth/logout', 		['as'=>'authLogout',	'uses'=>'Auth\AuthController@getLogout']);
	Route::get('/auth/login', 		['as'=>'authLogin', 	'uses'=>'Auth\AuthController@getLogin']);
	Route::post('/product/vote', 	['as'=>'product.vote', 	'uses'=>'Frontend\IndexController@postVote']);
	Route::get('/search', 			['as'=>'search.product','uses'=>'Frontend\IndexController@search']);
	
	Route::get('/productCompare', 						['as'=>'productCompare.index', 		'uses'=>'Frontend\CompareListController@index']);
	Route::delete('/productCompare/{productCompare}', 	['as'=>'productCompare.destroy', 	'uses'=>'Frontend\CompareListController@destroy']);
	Route::match(['put', 'patch'],'/productCompare/{productCompare}', ['as'=>'productCompare.update', 'uses'=>'Frontend\CompareListController@update']);
	
	Route::get('/wishlist',					['as'=>'wishlist.index', 	'uses'=>'Frontend\WishListController@index']);
	Route::post('/wishlist',				['as'=>'wishlist.store', 	'uses'=>'Frontend\WishListController@store']);
	Route::delete('/wishlist/{wishlist}',	['as'=>'wishlist.destroy', 	'uses'=>'Frontend\WishListController@destroy']);
	
	Route::get('/product',			['as'=>'product.index', 	'uses'=>'Frontend\IndexController@index']);
	Route::get('/product/{product}',['as'=>'product.show', 		'uses'=>'Frontend\IndexController@show']);
	
	Route::get('/cart',				['as'=>'cart.index', 				'uses'=>'Frontend\CartController@index']);
	Route::post('/cart',			['as'=>'cart.store', 				'uses'=>'Frontend\CartController@store']);
	Route::delete('/cart/{cart}',	['as'=>'cart.destroy', 				'uses'=>'Frontend\CartController@destroy']);
	Route::match(['put','patch'],'/cart/{cart}',['as'=>'cart.update', 	'uses'=>'Frontend\CartController@update']);

	Route::get('/checkout',		['as'=>'cart.checkout', 'uses'=>'Frontend\CartController@getCheckout']);
	Route::get('/contact', 		['as'=>'contact', 		'uses'=>'Frontend\IndexController@getContact']);
	Route::post('/contact', 	['as'=>'contact', 		'uses'=>'Frontend\IndexController@postContact']);
	Route::post('/checkout',	['as'=>'cart.checkout', 'uses'=>'Frontend\CartController@postCheckout']);
	Route::match(['put','patch'],'/myaccount/{id}/EditPassword', ['as'=>'myaccount.edit.password', 'uses'=>'Frontend\MyAccountController@update_password']);
	Route::get('/myaccount/{id}/EditPassword', ['as'=>'myaccount.edit.password', 'uses'=>'Frontend\MyAccountController@edit_password']);
	Route::get('myaccount',	['as'=>'myaccount.index', 'uses'=>'Frontend\MyAccountController@index']);
	Route::post('myaccount',	['as'=>'myaccount.store', 'uses'=>'Frontend\MyAccountController@store']);
	Route::get('myaccount/create',	['as'=>'myaccount.create', 'uses'=>'Frontend\MyAccountController@create']);
	Route::get('myaccount/{myaccount}/edit',	['as'=>'myaccount.edit', 'uses'=>'Frontend\MyAccountController@edit']);
	Route::match(['put','patch'],'myaccount/{myaccount}', ['as'=>'myaccount.update', 'uses'=>'Frontend\MyAccountController@update']);
});
//Route::resource('myaccount', 'Frontend\MyAccountController');
Route::group(["prefix" => "admin", "namespace" => "Admin", "middleware" => "auth"], function(){

		Route::get('/', 					['as'=>'adminIndex', 			'uses'=>'ProductController@index']);
		Route::resource("categories","CategoryController");
		Route::resource("products","ProductController");
		Route::post('/product/excel', 		['as'=>'product.import.excel', 	'uses'=>'ProductController@importProductFromExcelFile']);

		Route::get('/vote', 				['as'=>'admin.vote.index', 		'uses'=>'VoteController@index']);
		Route::delete('/vote/{vote}', 		['as'=>'admin.vote.destroy', 	'uses'=>'VoteController@destroy']);

		Route::get('/order', 				['as'=>'admin.order.index', 	'uses'=>'OrderController@index']);
		Route::get('/order/{order}/edit', 	['as'=>'admin.order.edit', 		'uses'=>'OrderController@edit']);
		Route::post('/order', 				['as'=>'admin.order.store', 	'uses'=>'OrderController@store']);
		Route::delete('/order/{order}', 	['as'=>'admin.order.destroy', 	'uses'=>'OrderController@destroy']);
		Route::get('/order/create', 		['as'=>'admin.order.create', 	'uses'=>'OrderController@create']);
		Route::get('/order/{order}', 		['as'=>'admin.order.show', 		'uses'=>'OrderController@show']);
		Route::match(['put','patch'],'/order/{order}', ['as'=>'admin.order.update', 'uses'=>'OrderController@update']);

		Route::get('/customer', 				['as'=>'admin.customer.index', 		'uses'=>'CustomerController@index']);
		Route::get('/customer/{customer}/edit', 	['as'=>'admin.customer.edit', 	'uses'=>'CustomerController@edit']);
		Route::post('/customer', 				['as'=>'admin.customer.store', 		'uses'=>'CustomerController@store']);
		Route::delete('/customer/{customer}', 	['as'=>'admin.customer.destroy', 	'uses'=>'CustomerController@destroy']);
		Route::get('/customer/create', 		['as'=>'admin.customer.create', 		'uses'=>'CustomerController@create']);
		Route::match(['put','patch'],'/customer/{customer}', ['as'=>'admin.customer.update', 'uses'=>'CustomerController@update']);

		Route::get('/user', 				['as'=>'admin.user.index', 		'uses'=>'UserController@index']);
		Route::get('/user/{user}/edit', 	['as'=>'admin.user.edit', 	'uses'=>'UserController@edit']);
		Route::post('/user', 				['as'=>'admin.user.store', 		'uses'=>'UserController@store']);
		Route::delete('/user/{user}', 	['as'=>'admin.user.destroy', 	'uses'=>'UserController@destroy']);
		Route::get('/user/create', 		['as'=>'admin.user.create', 		'uses'=>'UserController@create']);
		Route::match(['put','patch'],'/user/{user}', ['as'=>'admin.user.update', 'uses'=>'UserController@update']);
		Route::get('product/search',['as'=>'admin.product.search', 'uses'=>'ProductController@searchProduct']);
});

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    public function orderItem(){
    	return $this->hasMany('App\OrderItem');
    }
}

app/Http/Controllers/Admin/OrderController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Order;

class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $orders = Order::paginate(PAGINATE);
        return view('admin.orders.index')->with(compact('orders'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $order = Order::findOrFail($id);
        $orderItem = $order->orderItem;
        
        return view('admin.orders.show')->with(compact('order', 'orderItem'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $order = Order::findOrFail($id);
        return view('admin.orders.edit')->with(compact('order'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $order = Order::findOrFail($id);
        $data = $request->except('_token', '_method');
        $order->status = $data['status'];
        $order->payment_type = $data['payment'];
        $order->note = $data['note'];
        $order->deliver_date = $data['deliver_date'];
        $order->total = $data['total'];
        $order->save();

        return redirect()->route('admin.order.show',$order->id)->with('message','Update success!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $order = Order::findOrFail($id);
        $order->delete();
        return redirect()->route('admin.order.index')->with('message','Update success!');
    }
}

resources/views/admin/orders/create.blade.php
@extends('layouts.admin')

@section('content')
    <div class="page-header">
        <h1>Categories / Create </h1>
    </div>
    <div class="row">
        <div class="col-md-12">
            <form action="{{ action('Admin\CategoryController@store') }}" method="POST">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group">
                     <label for="name">NAME</label>
                     <input type="text" name="name" class="form-control" value="{{  Session::getOldInput('name') }}"/>
                </div>

            <a class="btn btn-default" href="{{ action('Admin\CategoryController@index') }}">Back</a>
            <button class="btn btn-primary" type="submit" >Create</a>
            </form>
        </div>
    </div>


@endsection

resources/views/admin/orders/edit.blade.php
@extends('layouts.admin')

@section('content')
    <div class="page-header">
        <h1>ORDER / Edit </h1>
    </div>
    <div class="row">
    @if(Session::has('message'))
        <div class="alert alert-success fade in">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong>{{ Session::get('message') }}</strong>
      </div>
    @endif
        <div class="col-md-12">
            <form action="{{ action('Admin\OrderController@update', $order->id) }}" method="POST">
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                
                <table class="table">
                    <tbody>
                      <tr class="success">
                        <td>ID</td>
                        <td>{{$order->id}}</td>
                    </tr>
                    <tr class="warning">
                        <td>Status</td>
                        <td>
                            <div class="form-group">
                              <select class="form-control" id="status" name="status" style="width:24% !important">
                                    <option value="0"<?php if($order->status == 0){echo "selected";} ?>>None</option>
                                    <option value="1" <?php if($order->status == 1){echo "selected";} ?>>Ordered</option>
                              </select>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>Payment</td>
                        <td>
                            <input type="text" name = "payment" value="{{ $order->payment_type }}" required>
                        </td>
                    </tr>
                        <td>Note</td>
                        <td>
                            <input type="text" name = "note" value="{{ $order->note }}" required>
                        </td>
                      </tr>
                      </tr>
                        <td>Deliver date</td>
                        <td>
                            <input type="text" name = "deliver_date" value="{{ $order->deliver_date }}" required>
                        </td>
                      </tr>
                      </tr>
                        <td>Total</td>
                        <td>
                            <input type="text" name = "total" value="{{ $order->total }}" required>
                        </td>
                      </tr>
                    </tbody>
                  </table>
            <a class="btn btn-default" href="{{ action('Admin\OrderController@index') }}">Back</a>
            <button class="btn btn-primary" type="submit" >Save</a>
            </form>
        </div>
    </div>


@endsection

resources/views/admin/orders/index.blade.php
@extends('layouts.admin')

@section('content')
    <div class="page-header">
        <h1>Orders</h1>
    </div>

  @if(Session::has('message'))
        <div class="alert alert-success fade in">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong>{{ Session::get('message') }}</strong>
      </div>
    @endif
    <div class="row">
        <div class="col-md-12">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>CUSTOMER</th>
                        <th>PAYMENT</th>
                        <th>NOTE</th>
                        <th>DELIVER</th>
                        <th>STATUS</th>
                        <th>TOTAL</th>
                        <th class="text-right">OPTIONS</th>
                    </tr>
                </thead>

                <tbody>

                @foreach($orders as $order)
                <tr>
                    <td>{{$order->id}}</td>
                    <td>
                        <a href ="#">
                            {{ App\Customer::findOrFail($order->customers_id)->name }}
                        </a>
                    </td>
                    <td>{{ $order->payment_type }}</td>
                    <td>{{ $order->note }}</td>
                    <td>{{ $order->deliver_date }}</td>
                    <td>
                        @if($order->status==1)
                            {{ 'Ordered' }}
                        @else
                            {{ 'None' }}
                        @endif
                    </td>
                    <td>{{ $order->total }}</td>
                    <td class="text-right">
                        <a class="btn btn-primary" href="{{ action('Admin\OrderController@show', $order->id) }}">View</a>
                        <a class="btn btn-warning " href="{{ action('Admin\OrderController@edit', $order->id) }}">Edit</a>
                        <form action="{{ action('Admin\OrderController@destroy', $order->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };"><input type="hidden" name="_method" value="DELETE"><input type="hidden" name="_token" value="{{ csrf_token() }}"> <button class="btn btn-danger" type="submit">Delete</button></form>
                    </td>
                </tr>

                @endforeach

                </tbody>
            </table>

        </div>
        {!! '<center>'.$orders->appends(Request::except('page'))->render().'</center>' !!}
    </div>
@endsection

resources/views/admin/orders/show.blade.php
@extends('layouts.admin')

@section('content')
    <div class="page-header">
        <h1>Order / Detail/{{ $order->id }} </h1>
    </div>
    @if(Session::has('message'))
        <div class="alert alert-success fade in">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong>{{ Session::get('message') }}</strong>
      </div>
    @endif
<table class="table">
    <thead>
      <tr>
        <th>NAME</th>
        <th>MODEL</th>
        <th>CODE</th>
        <th>CATEGORY</th>
        <th>SILK</th>
        <th>COLOR</th>
        <th>PRICE</th>
        <th>QUALTITY</th>
      </tr>
    </thead>
    <tbody>
    @foreach($orderItem as $item)
      <tr class="success">
        <td>
            <a href = "{{ route('admin.products.show', ['p_id'=>$item->product->id]) }}">
            {{ $item->product->name_ru }}
            </a>
        </td>
        <td>{{ $item->product->model }}</td>
        <td>{{ $item->product->artice_id }}</td>
        <td>
            <a href = "{{ route('admin.categories.show', ['cat_id'=>$item->product->category->id]) }}">
            {{ $item->product->category->name_ru }}
            </a>
        </td>
        <td>{{ $item->product->silk_id }}</td>
        <td>{{ $item->color->color_ru }}</td>
        <td>{{ $item->product->price }}</td>
        <td>{{ $item->quantity }}</td>
      </tr>
    @endforeach
    </tbody>
</table>

            <a class="btn btn-default" href="{{ action('Admin\OrderController@index', $order->id) }}">Back</a>
        </div>
    </div>


@endsection